#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
CONFIG_FILE=/etc/ss.json

start() {
    service_start /userdisk/sysapihttpd/ss/bin/ss-redir -c $CONFIG_FILE -b 0.0.0.0
}

stop() {
    service_stop /userdisk/sysapihttpd/ss/bin/ss-redir
}

restart() {
    stop
    start
}
